### ISSUE TITLE
How to use properly?

### ISSUE THREAD

**Issue by ThunderMods** [Rednick16/jailed_support#2]
Hello! I downloaded libsupport.dylib, injected, and i'm initiliazing this bypass in dispatch, but game still detects that it was sideloaded.
I just took your example, put and all, it still not work. Do i need to change bundle id, and add name of my cheat dylib in list which files to bypass?

**Comment by Rednick16** [comment]
Why would you call it in a dispatch? As soon as the app launches checks are active. Also you need to provide your apps bundle id. I’m closing this if there isn’t anything further.

**Comment by ThunderMods** [comment]
In my game, the all checks starts after you logged in. I fixed problem now and it working, thanks. Closing
